/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    CaseCreateDialog: typeof import('./components/cases/CaseCreateDialog.vue')['default']
    CaseSelectDialog: typeof import('./components/CaseSelectDialog.vue')['default']
    ChangePasswordDialog: typeof import('./components/ChangePasswordDialog.vue')['default']
    DataTablePage: typeof import('./components/DataTablePage.vue')['default']
    DialogFooter: typeof import('./components/DialogFooter.vue')['default']
    DriverCreateDialog: typeof import('./components/masters/DriverCreateDialog.vue')['default']
    ImportPreviewDialog: typeof import('./components/ImportPreviewDialog.vue')['default']
    MaskedId: typeof import('./components/MaskedId.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PrecheckResult: typeof import('./components/PrecheckResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
    TableRowActions: typeof import('./components/TableRowActions.vue')['default']
    VehicleFormFields: typeof import('./components/VehicleFormFields.vue')['default']
  }
}
